---@meta
--
---@class UnitTable
---@field name string
---@field class? ClassFile
--
---@class FilterValue
---@field Value any
---@field Title? string
---@field Tooltip? fun(tooltip: Tooltip, data: any)
--
---@class FilterDefinition
---@field Type "select"|"toggle"
---@field Name string
---@field Title? string
---@field Default? any
---@field Values? FilterValue[]
---@field Tooltip? fun(tooltip: Tooltip, data: any)
--
---@alias FilterDescription FilterDefinition[]
